### ISSUE TITLE
Tracking issue for documentation

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#401]
Use this comment to add points that should be addressed in documentation.

- [ ] It is more difficult to add new properties than delete existing ones, when importing a schema file, be select any that may be relevant.
- [ ] It is even more difficult to add new classes and you cannot add properties to a mapping from a class that was not selected when the schema is uploaded, so the documentation should emphasize that the user needs to be very extensive in the classes they select.
- [x] #327
  - [ ] #336
- [ ] How to add & delete properties from a schema after upload, & possible consequences of doing so.
- [ ] How to delete properties from the spine that got added accidentally & possible consequenses of doing so.
- [ ] How does the tool determine classes and properties from the schema file uploaded, and how they are associated? E.g. for RDF I know rdfs:Class and rdfs:Property are used, but suspect owl:Class is not. What are the equivalents for XSD and JSON-Schema.
- [ ] What XML/XSD features are supported? (nothing supports them all)
- [ ] How to deal with multipart schema, i.e. >1 xsd file? especially when there are subfolders.

**Comment by philbarker** [comment]
- [ ] #327

**Comment by edgarf** [comment]
@dlawsonQIP @AH1CEDS - We are going to close this issue, however if you are still using this check-list, feel free to reopen.
